services:
  fika:
    image: docker.io/dildz/spt-fika-3.9.8:latest
    container_name: fika
    environment:
      - HOST_USER=${USER}   # Passes the host's username into the container
    volumes:
      - ${HOME}/docker/containers/spt-fika/server:/opt/server    # Dynamic server directory path
      - ${HOME}/docker/logs:/home/${USER}/docker/logs            # Dynamic log directory path
    ports:
      - "6969:6969"
    command: [ "bash", "/opt/init-server.sh" ]
    restart: unless-stopped
